### ISSUE TITLE
Load eBird data into R for Australia

### ISSUE THREAD

**Issue by coreytcallaghan** [Josh-Lee1/eBird-Fire-Index#1]
Any luck on this yet @Josh-Lee1?

**Comment by Josh-Lee1** [comment]
Hi Corey,
I split the file into many, each with 100,000 lines.
I loaded the one in ok and looks good but haven't figured out how to get it
all in at once.

Congratulations on the bub!

**Comment by coreytcallaghan** [comment]
How much RAM do you have? How many 'chunks' does it take with 100,000 rows each? Manageable?

I think you should figure out (a) the columns we'll need for analyses and (b) how to read in those specific columns. I think ```readr::read_delim``` does this well.

You should be able to handle more than 100k at a time, so could try 1 million?

**Comment by Josh-Lee1** [comment]
I have 16GB.
Do you mean how many 100,000line files are there? If so 230.

**Comment by coreytcallaghan** [comment]
Yeah, that is what I meant. Hmmm. Sounds like progress. It would be good to
find a larger number that R can handle easily and then split it into a few
less files perhaps?

You don't necessarily need to read it ALL into R at one time. First step
could be to write a function that extracts the best data from each file and
saves that and then join those together? What do you think @wcornwell?
