### ISSUE TITLE
Matching with trait data

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#10]
I'm thinking feeding guilds will be the most interesting, personally.  But @Josh-Lee1 should make final call on what to look at

**Comment by Josh-Lee1** [comment]
That sound's good.
Should the decision be based on what we expect will give a strong result,
or what hasn't been done, or what might have implications for conservation?
I will have a little look around the literature but otherwise feeding
guilds could be a good one.

**Comment by coreytcallaghan** [comment]
Some mix of these, based on your hypotheses!

Let me know if you need help wrangling the trait data. This is where I have downloaded it from in the past: https://www.nature.com/articles/sdata201561

**Comment by Josh-Lee1** [comment]
Thanks Corey, 
I'm just looking around the paper but cant find a download? is getting hands on the data more complicated than that?

**Comment by coreytcallaghan** [comment]
Yeah. The link to figshare or something should be somewhere in there.

**Comment by wcornwell** [comment]
Not easy to find....

http://dx.doi.org/10.6084/m9.figshare.1499292

**Comment by Josh-Lee1** [comment]
Got it! 
I'm happy to get going with feeding guilds. Looks like there are papers on the subject and I feel like it could be approached from a few angles. 
If this step is easy would it be possible to try with a few things? Might be fun to use @coreytcallaghan's urbanness index or something? 

Shall I create a subset df with just food columns for the next bit of processing?

**Comment by Josh-Lee1** [comment]
Actually I would be interested in using feeding aggregation as well if its possible.

**Comment by coreytcallaghan** [comment]
Sounds good! Sounds like some hypotheses are forming. :)

**Comment by Josh-Lee1** [comment]
I stuck the trait data and the coefficients df together. In a pretty cluncky way but i think it works. 
Then made some boxplots to look at the data. Not completely sure I did this right. I just used the before.after coefficient (ignoring the intercept)?. I pushed if you want to have a look. 
Thanks.

**Comment by wcornwell** [comment]
Yeah ignore the intercept which is just "how common is that species" in general.  Some interesting stuff in there, but I don't fully get the categories.  and some are very small sample size

some fun with `gghalves`

![image](https://user-images.githubusercontent.com/5534161/88364380-ffacfd80-cdc5-11ea-848f-12139f22a094.png)

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/88364534-8a8df800-cdc6-11ea-8674-efe77de4ea97.png)

**Comment by wcornwell** [comment]
```{r}
library(gghalves)

# default
ggplot(values, aes(x = as.factor(X171_Food_Intertidal_invertebrates_10), y = Estimate, fill = X171_Food_Intertidal_invertebrates_10)) +
  geom_half_boxplot(nudge = -0.1, outlier.color = NA) +
  geom_half_point() +
  theme_light() +
  guides(color = guide_legend(nrow = 1))+
  theme(legend.position = "none")
```

**Comment by coreytcallaghan** [comment]
These are looking great!

I guess when we pick hypotheses/traits, we'll want something where we have
some variability over...

**Comment by Josh-Lee1** [comment]
Cool! well if you think these are ok then I might play with some other things cause i didn't get anything dramatic and exciting.

**Comment by wcornwell** [comment]
I don't know--I think there is exciting stuff in there.  But be good to write down some specific hypotheses (ideally from the literature) before hunting through lots of traits.

**Comment by Josh-Lee1** [comment]
Ahk cool.
