### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by Josh-Lee1** [Josh-Lee1/eBird-Fire-Index#11]
![Rplot](https://user-images.githubusercontent.com/59299694/88514859-1fdef580-d02e-11ea-99b4-bb6e74230680.png)

So are we sure that a positive Estimate value is more post fire birds? this looks like specialists were doing better? P-value=0.00113

**Comment by Josh-Lee1** [comment]
![Species Responses](https://user-images.githubusercontent.com/59299694/88521015-b5cb4e00-d037-11ea-9c17-27838f241757.png)

**Comment by Josh-Lee1** [comment]
![Species responses 2](https://user-images.githubusercontent.com/59299694/88530991-84f21580-d045-11ea-8fbf-aa1e4484fd3a.png)

Hey @wcornwell  and @coreytcallaghan,

I am trying to understand why the "estimate" from the model is different to the after-before measure. Also why has it inverted? 
But is this the one i want? 
Thanks!

**Comment by wcornwell** [comment]
Yes that's the one you want but multiply by -1.  It's the coefficient for the "before" case.

**Comment by Josh-Lee1** [comment]
hmmmk cool thanks Will!

**Comment by Josh-Lee1** [comment]
[mobilitymodel.pdf](https://github.com/Josh-Lee1/eBird-Fire-Index/files/4985483/mobilitymodel.pdf)
[sizemodel.pdf](https://github.com/Josh-Lee1/eBird-Fire-Index/files/4985484/sizemodel.pdf)
[foodmodel.pdf](https://github.com/Josh-Lee1/eBird-Fire-Index/files/4985485/foodmodel.pdf)
[habitatmodel.pdf](https://github.com/Josh-Lee1/eBird-Fire-Index/files/4985486/habitatmodel.pdf)


![modelresults](https://user-images.githubusercontent.com/59299694/88609415-66ccf980-d0c7-11ea-8ccc-01f3d2cdbd42.PNG)

What do you think?

**Comment by wcornwell** [comment]
Looking good!

Log-transform body size will probably help since it looks way right skewed.

**Comment by Josh-Lee1** [comment]
Yeah that's heaps better. Should I throw a fitted line on or anything?

**Comment by wcornwell** [comment]
Yeah why not?

On Tue, Jul 28, 2020 at 12:20 PM Josh-Lee1 <notifications@github.com> wrote:
>
> Yeah that's heaps better. Should I throw a fitted line on or anything?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Associate Professor, School of Biological, Earth and Environmental
Sciences, UNSW
www.willcornwell.org    @will_cornwell
