### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by Josh-Lee1** [Josh-Lee1/eBird-Fire-Index#12]
Hey @wcornwell  and @coreytcallaghan , 
So I've been trying to plug a leak but can't seem to manage a fix. 
When I joined the trait data to the model coefficients, 13 species were lost due to spelling/name differences in the two data sets. 
I have located the species and wrote this code:
traitseds<- recode(foodtraits$species_name, 'Black-faced_Cuckoo-shrike' = "Black-faced_Cuckooshrike",
                  'European_Common_Blackbird' = "Eurasian_Blackbird",
                  'European_Common_Starling' = "European_Starling",
                  'Grey_Butcherbird' = "Gray_Butcherbird",
                  'Grey_Fantail' = "Gray_Fantail",
                  'Grey_Shrike-thrush' = "Gray_Shrikethrush",
                  'Australian_Wood_Duck' = "Maned_Duck",
                  'Red-browed_Finch' = "Red-browed_Firetail",
                  'Scarlet_Honeyeater' = "Scarlet_Myzomela",
                  'Superb_Fairy-wren' = "Superb_Fairywren",
                  'Variegated_Fairy-wren' = "Variegated_Fairywren",
                  'Willie_Wagtail' = "Willie-wagtail", 
                  'Jacky_Winter' = "Jacky-winter")
but I can't get her to go. 
I'll push the changes in case you would like to have a look.

**Comment by wcornwell** [comment]
problem was just above.  try this:

```{r}
foodtraits<- traits %>% 
  select("X3_Taxon_common_name_2", "X99_Body_mass_average_8", "X163_Food_Fruit_10":"X173_Food_fish_or_invertebrates_Inland_waters_10", "X115_Feeding_habitat_Terrestrial_Arid_shrubland_9":"X145_Feeding_habitat_Urban_landscapes_9", "X193_National_movement_local_dispersal_13":"X197_National_movement_Irruptive_13") %>% 
  rename(species = "X3_Taxon_common_name_2") %>% 
  mutate(species=gsub(" ", "_", species)) 
  

#### needs fixing!!!

traitseds<- recode(foodtraits$species, 'Black-faced_Cuckoo-shrike' = "Black-faced_Cuckooshrike",
                  'European_Common_Blackbird' = "Eurasian_Blackbird",
                  'European_Common_Starling' = "European_Starling",
                  'Grey_Butcherbird' = "Gray_Butcherbird",
                  'Grey_Fantail' = "Gray_Fantail",
                  'Grey_Shrike-thrush' = "Gray_Shrikethrush",
                  'Australian_Wood_Duck' = "Maned_Duck",
                  'Red-browed_Finch' = "Red-browed_Firetail",
                  'Scarlet_Honeyeater' = "Scarlet_Myzomela",
                  'Superb_Fairy-wren' = "Superb_Fairywren",
                  'Variegated_Fairy-wren' = "Variegated_Fairywren",
                  'Willie_Wagtail' = "Willie-wagtail", 
                  'Jacky_Winter' = "Jacky-winter")
```

**Comment by Josh-Lee1** [comment]
Thank you! 
But now I have a list of names with corrected species separate from the trait data frame. 
Is there I way I can recode and replace in one move?

**Comment by wcornwell** [comment]
```{r}
foodtraits$species <- recode(foodtraits$species, 'Black-faced_Cuckoo-shrike' = "Black-faced_Cuckooshrike",
                  'European_Common_Blackbird' = "Eurasian_Blackbird",
                  'European_Common_Starling' = "European_Starling",
                  'Grey_Butcherbird' = "Gray_Butcherbird",
                  'Grey_Fantail' = "Gray_Fantail",
                  'Grey_Shrike-thrush' = "Gray_Shrikethrush",
                  'Australian_Wood_Duck' = "Maned_Duck",
                  'Red-browed_Finch' = "Red-browed_Firetail",
                  'Scarlet_Honeyeater' = "Scarlet_Myzomela",
                  'Superb_Fairy-wren' = "Superb_Fairywren",
                  'Variegated_Fairy-wren' = "Variegated_Fairywren",
                  'Willie_Wagtail' = "Willie-wagtail", 
                  'Jacky_Winter' = "Jacky-winter")
```

**Comment by Josh-Lee1** [comment]
Oh of course. haha thanks ok should be good now!

**Comment by Josh-Lee1** [comment]
![map](https://user-images.githubusercontent.com/59299694/88627835-54b38100-d0f0-11ea-9cb1-50015e20bfd7.png)

So I made a map of all of the checklists inside the fire boundary. 
Is it a real hassle to get a basemap/shapefile for Aus underneath? and will it look rubbish without it?

**Comment by coreytcallaghan** [comment]
It is not a hassle!

Try googling it, but you can download one easily from 'rnaturalearth'
package. If you get stuck, let me know and I can chuck one into the
repository.

And it looks kinda rubbish without it... :)

**Comment by wcornwell** [comment]
https://ropensci.org/tutorials/rnaturalearth_tutorial/

remember that we're dropping everything about -25 S so, all that stuff in FNQ and the top end is out.

**Comment by coreytcallaghan** [comment]
True. The trick is to download as an 'sf' object directly. Then can easily
plot with geom_sf(data=australia) in ggplot2.

**Comment by Josh-Lee1** [comment]
Amazing. Thanks! I'll let you know how I go.
Should I cut at 25degrees at the end or all the bits before it goes together?

**Comment by coreytcallaghan** [comment]
half a dozen of one or six of the other....

**Comment by Josh-Lee1** [comment]
I got an outline of Aus but I guess I need to turn it into a sf? but I need to know coordinate system for that? i cant see any data with the map.

**Comment by Josh-Lee1** [comment]
Something like this?
ne_download(scale = 110, type = "countries", category = c("physical"), destdir = tempdir(), load = TRUE, returnclass = c("sf"))
It says that it cant reach the website...?

**Comment by coreytcallaghan** [comment]
Try this:
 ```
library(rnaturalearth)
library(sf)
library(ggplot2)

aus <- ne_countries(country="australia", returnclass="sf")

ggplot()+
  geom_sf(data=aus, fill="orange")
```

**Comment by coreytcallaghan** [comment]
And then should be able to add other layers to the plot. Let me know if it works.

**Comment by Josh-Lee1** [comment]
Error in st_as_sfc.SpatialPolygons(sp::geometry(x), ...) : 
  package rgeos required for finding out which hole belongs to which exterior ring

**Comment by Josh-Lee1** [comment]
Ah dont worry just needed that package

**Comment by coreytcallaghan** [comment]
try making sure rgeos and sp are installed I reckon? The code I just pasted
works for me on my machine....

**Comment by coreytcallaghan** [comment]
I WAS worried.

**Comment by Josh-Lee1** [comment]
My next obstacles are rearranging layers so that the base map is actually on the base.
and also cropping at 25 degrees. 
The former has crashed R twice so I think I'm trying the wrong things. Any tips?

**Comment by coreytcallaghan** [comment]
Should just be something like:

```
ggplot()+
geom_sf(data=australia)+
geom_sf(data=points)+
geom_sf(data=fire_extent)+
xlim(x1, x2)+
ylim(y1, y2)+
coord_equal()

```

**Comment by Josh-Lee1** [comment]
Finally got it! You said it wouldn't be a hassle haha 
Thanks!

**Comment by coreytcallaghan** [comment]
![image](https://user-images.githubusercontent.com/28123686/88649287-17102180-d10b-11ea-862f-9069ffb48e28.png)

**Comment by Josh-Lee1** [comment]
![map](https://user-images.githubusercontent.com/59299694/88654519-d61b0b80-d110-11ea-9806-97a3691dd9c3.png)
Hahaha
