### ISSUE TITLE
adding estimted day of fire for each ebird checklist

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#13]

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/90700780-0b5ae980-e2ca-11ea-9465-3f04f0b4be57.png)

**Comment by wcornwell** [comment]
still dropping a few points, so trying a slightly larger buffer now

**Comment by coreytcallaghan** [comment]
Sweet. Looks good to me!

**Comment by Josh-Lee1** [comment]
Very cool!

**Comment by wcornwell** [comment]
this is done I think.  changes here: https://github.com/Josh-Lee1/eBird-Fire-Index/commit/58e02d4a8f07b94de3e2121791bc89ebfa276787

**Comment by wcornwell** [comment]
I re-ran all the models and the results look pretty similar.  @Josh-Lee1 can you double check this?

**Comment by Josh-Lee1** [comment]
Hey Will, 
Yeah a few species changed order a bit but generally looks quite similar. Cool!

**Comment by wcornwell** [comment]
do we want to make a prettier version of the map above as a supplementary figure?

**Comment by coreytcallaghan** [comment]
I am always pro supp figures, so if you already did it to some extent, I
vote yes.
