### ISSUE TITLE
organizing repo

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#14]
hey @Josh-Lee1 can you organize the repo and the workflow a bit?  Was trying to figure out how to plug #13 into the analysis but I got a bit confused about where the important stuff is.  

We'll come back to this lots in the next several months (e.g. after we get this into peer review) so it's work doing a bit of clean up at this stage.

**Comment by Josh-Lee1** [comment]
Sure thing. 
Do you just want me to organise folders and rename some of the files so they make more sense?
Will this mean that we need to change our code to match new file names/locations?

**Comment by wcornwell** [comment]
yes and yes!

**Comment by wcornwell** [comment]
check out this blog on the topic: https://nicercode.github.io/blog/2013-05-17-organising-my-project/

**Comment by Josh-Lee1** [comment]
Oh great thanks Will. 
I will get it all sorted tomorrow!
Josh

**Comment by Josh-Lee1** [comment]
Hey Will I have reorganised the folders/files. 
I seem to be having trouble committing and pushing the changes, Rstudio keeps crashing. 
Am I right in thinking that after I push the changes you will be able to pull and the files will reorganise on your machine too?

**Comment by coreytcallaghan** [comment]
Yup, that's right! Hopefully you are able to push the changes. :)

**Comment by wcornwell** [comment]
any luck?

**Comment by Josh-Lee1** [comment]
Hey Will sorry ive been away.
No Im not sure if it was r or git that was struggling to commit all the
changes. My R session broke a few times so apart from just keeping trying
not sure what else to try.

**Comment by wcornwell** [comment]
no worries.  can discuss at meeting...

**Comment by Josh-Lee1** [comment]
I finally pushed the changes to the files. I think because I moved all the data around it was quite a lot for git to handle. 
I have to run through the code to edit file locations now.

**Comment by coreytcallaghan** [comment]
Awesome, sounds good!

**Comment by wcornwell** [comment]
sweet
