### ISSUE TITLE
dealing with fire severity

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#15]
FESM atm

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/91920289-ede74000-ed0b-11ea-9f06-3ab9a67317e5.png)

one way to do this.  this is only the after checklists and just the distribution of fire severities where the bird was observed.

**Comment by coreytcallaghan** [comment]
Ah, so you are thinking a 'separate' mini-analysis, but yet still opens up the door for some discussion, etc...?

**Comment by wcornwell** [comment]
yup

**Comment by coreytcallaghan** [comment]
I'm indifferent. Seems like that would play to the 'get it out' approach well. :)

**Comment by wcornwell** [comment]
i think some of the "increasing species" are just playing around the edges of the fire and in low severity areas.

**Comment by coreytcallaghan** [comment]
Yup, was thinking that using this as an aid in interpreting the 'main' results would be good then in that instance.

**Comment by Josh-Lee1** [comment]
Very cool! 
That all sounds good to me. Do we need to make one with before checklists to observe change?

**Comment by wcornwell** [comment]
Yeah I know what you mean--did the birds move?  or were they just in areas that burned severely?--but I'm a bit confused how to do that analysis.  Any clever ideas welcome.

**Comment by coreytcallaghan** [comment]
Where is the average severity in area around checklist data? I want to add it to this dataset: ```data_df_with_date<-read.csv("processed_data/ebird_data_with_fire_dates.csv")```

**Comment by wcornwell** [comment]
```
data_df<-read_csv("processed_data/ebird_data_with_fire_dates.csv")


final_sl_dat <- data_df %>%
  #  bind_rows(lists_without) %>%
  dplyr::filter(!is.na(day_of_fire)) %>%
  mutate(DURATION.MINUTES=as.numeric(DURATION.MINUTES),
         EFFORT.DISTANCE.KM=as.numeric(EFFORT.DISTANCE.KM)) %>%
  mutate(MONTH=month(OBSERVATION.DATE)) %>%
  mutate(before.after=ifelse(OBSERVATION.DATE>day_of_fire, "After", "Before")) %>%
  filter(before.after=="After")



fesm1000<-raster("Data/Raw/fesm_geotiff/fesm1000.tif")
b<-SpatialPointsDataFrame(cbind(final_sl_dat$LONGITUDE,final_sl_dat$LATITUDE), final_sl_dat, match.ID = FALSE,
                          proj4string = CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"))
bb<-spTransform(b,crs(fesm1000))
final_sl_dat$sev<-extract(fesm1000,bb)
```

**Comment by coreytcallaghan** [comment]
Don't we just want to model this somehow:

![image](https://user-images.githubusercontent.com/28123686/91928805-550eef80-ed20-11ea-8b89-c14cf289c506.png)

Note that ```geom_jitter``` was used.

**Comment by wcornwell** [comment]
yes *somehow*. 

It's not a nice neat linear model problem.  fire severity for the before observations (ie severity of the future fire) is quite confusing.

**Comment by wcornwell** [comment]
could be a before/after * severity interaction, maybe?

**Comment by wcornwell** [comment]
possible figure:

![image](https://user-images.githubusercontent.com/5534161/92667491-68890e80-f34f-11ea-966d-2ed2cebb1b67.png)


any thoughts?

**Comment by coreytcallaghan** [comment]
I think this is solid. It will definitely help with writing the discussion a bit. And is probably the focal point for a whole paragraph. We can make an interactive version and host it on github and link to it, too. So people can see what species are which....

**Comment by Josh-Lee1** [comment]
Very cool!
Is the trendline for all species?
And will we have something like this for all traits?

**Comment by coreytcallaghan** [comment]
I don't think it is necessary for all traits, but tailor it to what we want to write our discussion around, in my opinion.

@wcornwell can you just paste the df underlying this plot into an RDS somewhere and let me know where. I'll try making an interactive figure and putting it in this repository.

**Comment by wcornwell** [comment]
```{r}
library(readr)
library(plotly)
oo<-read_csv("processed_data/severity_data_and_traits.csv")
z<-ggplot(oo,aes(x=median.sev,y=-1*Estimate,label=COMMON.NAME,))+
  geom_point(aes(col=feeding_specialisation))+geom_smooth(method="lm")+ylab("modeled response to fire")+
  geom_hline(yintercept = 0,linetype="dashed")+xlab("Median fire severity in post-fire observations")+
  theme_classic()

ggplotly(z)
```

**Comment by coreytcallaghan** [comment]
Hey @Josh-Lee1 can you go into your settings and flick github pages on?

Should look something like this:

![image](https://user-images.githubusercontent.com/28123686/92668614-a6d3fd00-f352-11ea-9253-f4b0371f3447.png)

**Comment by Josh-Lee1** [comment]
Ok done. Let me know if I clicked the wrong button.

**Comment by coreytcallaghan** [comment]
Sweet - this link should be live now and sharable with anyone: https://josh-lee1.github.io/eBird-Fire-Index/interactive_figure.html

**Comment by Josh-Lee1** [comment]
Cool! Thanks Corey.

**Comment by coreytcallaghan** [comment]
We can pretty it up once we have an idea of what the final figure will look like.

**Comment by Josh-Lee1** [comment]
Hey @wcornwell 
Just want to clarify that you have called anything with 2 or more feeding guilds a generalist and specialists only have 1? 
Thanks
