### ISSUE TITLE
waterbirds?

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#16]
exclude or discuss?

**Comment by wcornwell** [comment]
leaning towards exclude

**Comment by Josh-Lee1** [comment]
Hey @wcornwell and @coreytcallaghan , 
Just wondering on what basis we will exclude species? 
From scanning the list I would have said that about 8 species (of 85 total) could be excluded as waterbirds, however I checked species that use inland waters/coastal habitats according to the trait data and the list grows considerably (to 19). 
Does our decision about what to exclude need to be based on some objective metric or do we just get rid of things we think that we should?

**Comment by coreytcallaghan** [comment]
It depends, but I would have thought by order or family somehow. So remove ardeidae, or Phalacrocoracidae. Or by order, like charadriiformes...?

**Comment by Josh-Lee1** [comment]
Oh righto. So then would something like WB Sea-Eagle be left in? I would have said that a Masked lapwing was more terrestrial than a sea eagle?

**Comment by coreytcallaghan** [comment]
Hmm. It gets tricky, at some point there will have to be some discussion about this or that species that doesn't 'make sense' in our analysis, like White-bellied Sea-Eagle potentially. But there probably isn't a right or wrong way to go about it...

**Comment by Josh-Lee1** [comment]
Yeah ok. Thanks Corey. 
So should i just remove things that seem sensible for now and rerun the analysis for now?

**Comment by coreytcallaghan** [comment]
Sounds reasonable.

**Comment by Josh-Lee1** [comment]
Hey team, 
so I removed 9 species from 5 families. 
Here are the results rerun. Feeding specialism is still significant but size and sedentism no longer (also all the waterbirds seem to be all the "mobile" birds so the sedentism test looks pretty lame now)
![image](https://user-images.githubusercontent.com/59299694/91922098-6d770e00-ed10-11ea-8e66-f095c18012ee.png)

**Comment by wcornwell** [comment]
Guess that's the result for land birds.  let's go with it
