### ISSUE TITLE
spatial term in the model

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#17]
check out if there is a better way to deal with

**Comment by coreytcallaghan** [comment]
Added a spatial term to model @Josh-Lee1. I think I re-ran all the models. Let us know if the model results change much?

**Comment by Josh-Lee1** [comment]
Hey just a github question. 
So I am running the code on my machine now to check the results. Is this needed if you ran the code already and pushed?

**Comment by coreytcallaghan** [comment]
I think I already ran it.

**Comment by Josh-Lee1** [comment]
![image](https://user-images.githubusercontent.com/59299694/92067391-81da0a00-ede7-11ea-978a-174929e02b0c.png)
Here are the results again, same story. 

I will have a look at the species too.

**Comment by Josh-Lee1** [comment]
![image](https://user-images.githubusercontent.com/59299694/92067655-29573c80-ede8-11ea-997a-83bbbc3a8674.png)

**Comment by coreytcallaghan** [comment]
I am closing this one @Josh-Lee1, as I think we've done this. It will put some reviewers at bay at least.

**Comment by Josh-Lee1** [comment]
Thanks Corey.
