### ISSUE TITLE
new version of ms

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#18]
I think we're good on results, and now back to the writing.  discuss shortly....

**Comment by coreytcallaghan** [comment]
@Josh-Lee1 is there anything else you need from me or Will? Or are we waiting for an updated manuscript draft etc.? No rush whatsoever, I'm just checking is all.

**Comment by Josh-Lee1** [comment]
Thanks Corey, 
So for figures/results I have: 
Map of checklists/fire boundary
Ranked list of species fire responses (With waterbirds removed, and updated model terms)
Plots of trait correlations (with updated results)
Will's correlation between modelled response and severity for feeding specialism

I had some classes cancelled today so will spend some time on this.

**Comment by coreytcallaghan** [comment]
Yup - that sounds good!

And sorry - forgot you had your week of honours classes. Seriously, no rush. I just wanted to make sure I wasn't needed for any coding or anything etc.
