### ISSUE TITLE
consistent list of species in the study

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#19]
I didn't manage to exclude waterbirds, so need to keep a list of species in the study somewhere so all the figures and analyses are looking at the same subset of data.

**Comment by coreytcallaghan** [comment]
Good idea. Probably worth making this an appendix table s1 or something of the like as well, with the trait data etc. Makes the reproducibility/open access aspect of the manuscript easier down the road.
