### ISSUE TITLE
Scoping of data

### ISSUE THREAD

**Issue by coreytcallaghan** [Josh-Lee1/eBird-Fire-Index#2]
See how much data we have from eBird throughout the fire spot.

Maybe both 'before' and 'after' fires?

**Comment by Josh-Lee1** [comment]
I'm imagining this step will be to filter all the obs by location and do a count.
Will there be a nice shapefile somewhere I can use to crop the data or another trick?

**Comment by Josh-Lee1** [comment]
Ok looks like there could be some usable shapefiles of bushfire boundaries I could use on Gov. websites.

**Comment by coreytcallaghan** [comment]
Yup - that's right! should check out the sf package (https://r-spatial.github.io/sf/articles/sf1.html) for our spatial analyses. @wcornwell knows more about the shapefiles and where to find them.

Spatial analyses are computationally expensive! So, before we do any spatial stuff we want to minimize the number of points we are intersecting with a shapefile of fire boundary. So, first, we should trim the data based on date and other criteria, and then make a separate file for 'spatial stuff' that is only the LOCALITY_ID and the SAMPLING_EVENT_IDENTIFIER.

Let me know if that makes sense.

**Comment by Josh-Lee1** [comment]
Yes that makes sense thanks for the help.

**Comment by Josh-Lee1** [comment]
Hey @coreytcallaghan and @wcornwell,
I have gone through the steps for the first stage of scoping. Pretty sure I did everything right but I did have a bit of trouble with the st_join and then translating into a plot (the output of the join gave me an output of NAs and 0s which ggplot didnt like so I just did some replacements). 
Let me know if there is anything I should change or what to do next. 
Thanks, 
Josh

**Comment by coreytcallaghan** [comment]
Are the figures somewhere that show the joined points?

**Comment by coreytcallaghan** [comment]
I think the next step will be functionalizing it to apply for all 230
individual files?

Perhaps we should chat next week about this step?

**Comment by Josh-Lee1** [comment]
![image](https://user-images.githubusercontent.com/59299694/85117847-d64b0000-b262-11ea-9766-17a212156ce2.png)

This is the final output, Blue is the fire extent, red is checklists outside and black checklists inside. 
there are only 122 checklists inside the fire shapefile after filtering.

**Comment by coreytcallaghan** [comment]
Sweet! That's not bad. I guess we'll just have to apply it for all the data
and see how much data we have, and importantly how much data we have before
and after the fires.
