### ISSUE TITLE
Range Sizes

### ISSUE THREAD

**Issue by Josh-Lee1** [Josh-Lee1/eBird-Fire-Index#20]
Hey @coreytcallaghan 
I'm pretty sure the taxonomies match up ok but missing 5 species (Golden Whistler, Silvereye, Yellow-tailed Black-cockatoo, Shining Bronze-cuckoo and Rose Robin). 

Is it possible that these species are missing from the data or are you sure they are in there? 

Thanks, 
Josh

**Comment by coreytcallaghan** [comment]
Hmm...

Not sure. They *should* be there. According to here, it appears they have range maps: http://datazone.birdlife.org/species/factsheet/rose-robin-petroica-rosea

Maybe go through the 5 and see if the have a different name or something and that's why they are missing?

**Comment by Josh-Lee1** [comment]
From googling around it doesn't seem like these species have any other common names. Is there a version of this dataset with scientific names?

**Comment by coreytcallaghan** [comment]
Ah, I see. Um probably somewhere.

But if it is only five species, the easiest thing is to probably just add them and manually grab the data for those five species from the datazone: http://datazone.birdlife.org/species/search

Like here:

![image](https://user-images.githubusercontent.com/28123686/112096319-57427980-8b9e-11eb-82c4-dd940abd0be2.png)

**Comment by Josh-Lee1** [comment]
Easy. Thanks.

**Comment by Josh-Lee1** [comment]
This data doesn't seem to match the file that you originally passed on to me. I've checked a few species and numbers look different after converting to miles to km. 
I'm looking at: Extent of Occurrence breeding/resident (km2)

**Comment by Josh-Lee1** [comment]
Yeah I think the numbers are off. 
If I fill in the five with Extent of Occurrence breeding/resident (km2) the lm is non significant and three of the five are major outliers.
I ran it without the five to compare and P = 0.0006. So looks like it will be a good result but need to find the right numbers.

**Comment by coreytcallaghan** [comment]
Okay. Let me try to have a look at it today or tomorrow.

**Comment by coreytcallaghan** [comment]
I just sent you a different range size dataset and Rose Robin is in there (by its scientific name), and also doesn't match the online eoo so they must be different.

Go with what is in the most recent data, but hopefully they are close to the other dataset I sent through.

Let me know how you go.

**Comment by Josh-Lee1** [comment]
![RS](https://user-images.githubusercontent.com/59299694/112258315-69b1d580-8cba-11eb-9f91-bd74868bbffb.PNG)

![image](https://user-images.githubusercontent.com/59299694/112258395-8d751b80-8cba-11eb-990f-637001b0d4fe.png)

**Comment by Josh-Lee1** [comment]
Yeah that data seemed to have everyone in it after I fixed a few name discrepancies. 
Do you think this data looks like it needs transforming?

**Comment by coreytcallaghan** [comment]
Sweet. Probably log10 for range size, yeah.

**Comment by Josh-Lee1** [comment]
![RSlog10](https://user-images.githubusercontent.com/59299694/112260126-7dab0680-8cbd-11eb-855f-13c70c54e6db.PNG)

This looks wrong...
Is ggplot (blah blah)+ scale_x_log10() what I'm supposed to do? 

Also aren't we supposed to transform before the model? if so then we didnt log transform bird size...

**Comment by Josh-Lee1** [comment]
![image](https://user-images.githubusercontent.com/59299694/112261675-6de0f180-8cc0-11eb-9728-c5d5c9782658.png)

Cause log transforming makes size significant... haha oops. 
How big of an issue is this for us?!?

**Comment by coreytcallaghan** [comment]
Hmm. Not a big issue. See what WKC thinks! Range size looks weird, so maybe
best not to log transform. Need to look at the model fit etc.

And yeah, I usually do +scale_x_log10() as well.

Good work though, and either way, it will be good to include this result
and figure as an additional panel on the previous one I think.

Let's set up a time to chat through all these things perhaps and then you
can go forth with the revisions! So close!
