### ISSUE TITLE
shapefile of fires

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#3]

**Comment by wcornwell** [comment]
![map_figure_of_fires_and_temperature](https://user-images.githubusercontent.com/5534161/84607380-4b7ba580-aef0-11ea-908b-534dc03b0451.png)

**Comment by wcornwell** [comment]
code from frog project

```
get_species_fire_summary <- function(species_name) {
  
  message(paste0("Analyzing ", species_name))
  
  load(paste0("Data/range_maps/", gsub(" ", "_", species_name), ".RData"))
  
  range <- range_map %>%
    st_as_sf() %>%
    st_transform(crs=st_crs(hotspot_points))
  
  points_within_range <- range %>%
    st_join(hotspot_points)
  
  overlap_extent_area <- range %>%
    st_intersection(extent) %>%
    st_area() %>%
    sum() %>%
    as.numeric()
  
  range_area <- range %>%
    st_area() %>%
    sum() %>%
    as.numeric()
  
  overlap_percentage <- (overlap_extent_area/range_area)*100
  
  dat_summary <- points_within_range %>%
    dplyr::select(id, latitude, longitude, temp_kelvin,
                  power, confidence, datetime) %>%
    st_set_geometry(NULL) %>%
    mutate(extent_percent_burn=overlap_percentage) %>%
    mutate(species=species_name)
  
  return(dat_summary)
  
}
```

**Comment by wcornwell** [comment]
Psuedo-code steps:
save all maps to a figures directory with informative names

1. Load one ebird file
2. Filter out (ie exclude) bad checklists
3. Select only useful columns (exclude others)
4. Select only distinct rows (exclude others)
5. Spatial processing
   5a. read in fire shapefile 
   5b. make map of fire shapefile
   5c. Convert ebird checklists to sf object with CRS code from fire shapefile
   5d. Make a map of the points using `ggplot` and `geom_sf` on the fire shapefile map
   5e. add column for inside/outside using `st_join`
   5f. make a map with points colored by inside/outside
6. write output file as rds to a directory called `processed_data`

**Comment by Josh-Lee1** [comment]
Hey @wcornwell and @coreytcallaghan,
Just getting stuck on 5c. a bit. 
Do I have to assign a CRS to my ebird data before I make it a sf object? 
and should st_as_sf() do the trick for this transformation? 
Thanks, 
Josh

**Comment by coreytcallaghan** [comment]
Nah. Part of making it an sf object. In the st as sf function, should be
able to set crs=st_crs(fire_object).

**Comment by Josh-Lee1** [comment]
Yeah I think I understand that line of code but cant get the checklists into an sf object
I bump into this error.
Error in st_sf(x, ..., agr = agr, sf_column_name = sf_column_name) : no simple features geometry column present

**Comment by coreytcallaghan** [comment]
Can you flick me an RDS real quick via email and Ill have a go?

**Comment by Josh-Lee1** [comment]
Did that make it past your auto reply?

**Comment by coreytcallaghan** [comment]
This should work:

```
ebird_points <- st_as_sf(data=baatrimmed, coords=c("LONGITUDE", "LATITUDE"), crs=st_crs(fireshape))
```

And it appears to work for me:

```
ggplot() + 
   geom_sf(data = fireshape, size = 0.1, color = "black", fill = "black") + 
   geom_sf(data=ebird_points, color="green")+
   ggtitle("Fire Boundary Plot") + 
   coord_sf()
```

**Comment by Josh-Lee1** [comment]
I got this error. cant find Longitude?
Error in lapply(x[coords], as.numeric) : argument "x" is missing, with no default

**Comment by coreytcallaghan** [comment]
Check the spelling and case of the word...?

**Comment by Josh-Lee1** [comment]
:/

**Comment by coreytcallaghan** [comment]
Still nothing? It just worked on my machine.

**Comment by Josh-Lee1** [comment]
Yeah no bingo. 
Could it have to do with needing to update R? I dont think im on the most recent version.

**Comment by Josh-Lee1** [comment]
Did you change any code above that chunk?

**Comment by coreytcallaghan** [comment]
Sorry! Need to remove the 'data=' in that code.

**Comment by coreytcallaghan** [comment]
Here is everything from that .Rmd into a chunk:

```
baa <- read_delim("C:/Users/CTC/Desktop/baa", "\t", escape_double = FALSE, trim_ws = TRUE)

colnames(baa) <- gsub(" ", ".", colnames(baa))

library(dplyr)

baatrimmed<- baa %>% 
  filter(ALL.SPECIES.REPORTED==1, EFFORT.DISTANCE.KM<10, DURATION.MINUTES<300, DURATION.MINUTES>10) %>% 
  select(SAMPLING.EVENT.IDENTIFIER, LOCALITY.ID, LATITUDE, LONGITUDE, OBSERVATION.DATE) %>% 
  distinct()

library(sf)
fireshape<- st_read("National_Indicative_Aggregated_Fire_Extent_Dataset_v20200211/National_Indicative_Aggregated_Fire_Extent_Dataset_v20200211.shp")

library(ggplot2)
ggplot() + 
  geom_sf(data = fireshape, size = 0.1, color = "black", fill = "black") + 
  ggtitle("Fire Boundary Plot") + 
  coord_sf()

ebird_points <- st_as_sf(baatrimmed, coords=c("LONGITUDE", "LATITUDE"), crs=st_crs(fireshape))

ggplot() + 
  geom_sf(data = fireshape, size = 0.1, color = "black", fill = "black") + 
  geom_sf(data=ebird_points, color="green")+
  ggtitle("Fire Boundary Plot") + 
  coord_sf()
```

**Comment by Josh-Lee1** [comment]
Haha ok sweet well I'll let you know how I go after I finish updating R.

**Comment by coreytcallaghan** [comment]
Oh the suspense!!

**Comment by Josh-Lee1** [comment]
![image](https://user-images.githubusercontent.com/59299694/84650946-801d4a80-af4c-11ea-889b-09a5de65fbcf.png)

Yipee! Thanks heaps. I will carry on tomorrow.

**Comment by Josh-Lee1** [comment]
So trying to figure out how st_join works, I have this line: 
st_join(ebird_points, fireshape)
It adds another column but is full of N/As. Do I need another argument in the function to tell it inside= true or something? or is there another function to apply? 
Thanks

**Comment by coreytcallaghan** [comment]
I'd recommend looking around on google for different vignettes and/or tutorials.

e.g., https://cran.r-project.org/web/packages/sf/vignettes/sf4.html#Joining_two_feature_sets_based_on_geometries

Sometimes if I can't get something to work, I try to find some very simple play data and wrap my head around something that way first.

**Comment by Josh-Lee1** [comment]
Ok thanks. Ill give that a go.
