### ISSUE TITLE
references

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#5]
trait data in here:

https://onlinelibrary.wiley.com/doi/full/10.1111/oik.06158

**Comment by wcornwell** [comment]
traits and fire: https://link.springer.com/article/10.1007/s10682-018-9927-6#Tab1

**Comment by wcornwell** [comment]
This is an important one:

https://www.sciencedirect.com/science/article/pii/S0378112714000103#!

**Comment by Josh-Lee1** [comment]
Thanks!
