### ISSUE TITLE
table of checklists

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#6]
<img width="418" alt="Screen Shot 2020-07-01 at 5 00 36 pm" src="https://user-images.githubusercontent.com/5534161/86213055-71759b00-bbbc-11ea-906b-676eb76ca328.png">

**Comment by wcornwell** [comment]
@coreytcallaghan

**Comment by coreytcallaghan** [comment]
Sweet! Looks like a decent amount of data to play with! I'm excited to see how this shakes out @Josh-Lee1!
