### ISSUE TITLE
Matching with species data

### ISSUE THREAD

**Issue by wcornwell** [Josh-Lee1/eBird-Fire-Index#7]
We should get out everything before and after from within the fire outline. There should be ~500,000 checklists which should correspond to 5,000,000 - 10,000,000 rows in the resulting dataframe so big but not tooooo big.

**Comment by Josh-Lee1** [comment]
Didnt we count 136962+5788 checklists in the fire (before and after dec15).
Where did you get the 500000 number from?

**Comment by wcornwell** [comment]
My bad--you're right.  Should even be a bit smaller then

**Comment by Josh-Lee1** [comment]
Hey @wcornwell and @coreytcallaghan, 
Ok I have had a go and pushed up some work (see matching_to_sp.R)
I did a semi_join which looks like it got all of the data from the checklists of interest for the first file (baa). 
I then started to play with writing the function. Wasn't sure if we want to filter out some of the columns this time as well. 
It would be great if you could have a look so I can see if it runs! 
Thanks, 
Josh

**Comment by coreytcallaghan** [comment]
It looks pretty good to me! Could always test it with the 'test data files' we put in before, but other words, should be able to let it ride!

We can chat Thursday to see how it went?

**Comment by Josh-Lee1** [comment]
Oh I'm sure I replied to this oops... 
Ok i'm pretty sure I've gotten the loop to work, its running now but it worked for the test folder. 
I am available before 10:30 and after 2 today if you want to discuss the next steps. 
Thanks

**Comment by coreytcallaghan** [comment]
After 2 is good.

**Comment by Josh-Lee1** [comment]
@wcornwell are you available to chat this arvo?

**Comment by wcornwell** [comment]
sure.  how about 4?

**Comment by coreytcallaghan** [comment]
Fine by me.

**Comment by Josh-Lee1** [comment]
Great. See you then.

**Comment by wcornwell** [comment]
how's this going?

**Comment by Josh-Lee1** [comment]
Something funny has happened to our dates. I am going to try and re run code to see at which point the data changes format.

**Comment by wcornwell** [comment]
try:

```
library(tidyverse)
library(lubridate)
setwd("rawspeciesdata/")


read_dat_function <- function(file_name) {
  
  dat <- readRDS(file_name)
  dat$OBSERVATION.DATE<-ymd(dat$OBSERVATION.DATE)
  return(dat)
}

files <- list.files("../rawspeciesdata/")
data <- lapply(files, read_dat_function)
```

**Comment by wcornwell** [comment]
but i'm still not getting enough checklists...
<img width="438" alt="Screen Shot 2020-07-13 at 2 21 39 pm" src="https://user-images.githubusercontent.com/5534161/87270737-5ee05780-c514-11ea-91d4-36c25bcebd9f.png">

**Comment by Josh-Lee1** [comment]
Yeah i went back when I first had this problem and I think something has gone amis early on because there are checklists from the 1980s but I'm pretty sure I requested data from 2015 from ebird?
Also I didn't filter out unwanted checklists in the second loop but that should have given us more than expected not less...

**Comment by wcornwell** [comment]
maybe 12060 is right, but I thought it would be ~140,000 from calculations on #6

**Comment by wcornwell** [comment]
other than less data, it looks pretty good....

<img width="423" alt="Screen Shot 2020-07-13 at 2 46 43 pm" src="https://user-images.githubusercontent.com/5534161/87271822-b8965100-c517-11ea-940a-d8a751e14ab2.png">

**Comment by wcornwell** [comment]
just pushed some changes.  looking good.  i'm still a bit worried we're dropping data somewhere, but even with what we have there are some cool results already

**Comment by Josh-Lee1** [comment]
Great, thanks heaps Will. 
I am just trying to figure out what things mean and how to make it run.

**Comment by Josh-Lee1** [comment]
On struggle street a bit with this step. I've been playing with the code and understanding parts but not been able to make other parts run for me. 
Will the results of the final step of the code you wrote make up our "before_after" variable for the GAM?
Sorry to be slow! Maybe its best to get my questions answered in our next meet.

**Comment by coreytcallaghan** [comment]
Happy to chat tomorrow morning (before 11), or at 1 tomorrow.

**Comment by wcornwell** [comment]
> Will the results of the final step of the code you wrote make up our "before_after" variable for the GAM?

yeah, but not perfectly set up for that yet.

9:30 tomorrow?

**Comment by Josh-Lee1** [comment]
Yeah 9.30 works for me.
Thanks heaps.

**Comment by coreytcallaghan** [comment]
Ditto
